### ISSUE TITLE
Wrong Description of Reflect.deleteProperty()

### ISSUE THREAD

**Issue by Amit197** [mdn/sprints#3831] opened 2020-10-24 18:05 UTC
![image](https://user-images.githubusercontent.com/42664741/97088850-5ccc7f80-1651-11eb-9e72-f1947602f757.png)

**Comment by hamishwillee** [comment] 2020-10-25 22:11
Duplicate of #3826

**Comment by hamishwillee** [comment] 2020-10-25 22:11
Thanks for posting!

**Closed by hamishwillee** 2020-10-25 22:11 UTC
