### ISSUE TITLE
broken interactive canvas pixel buffer examples

### ISSUE THREAD

**Issue by Feirell** [mdn/sprints#3208] opened 2020-05-03 19:11 UTC
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The two interactive examples on https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Pixel_manipulation_with_canvas are broken in Firefox. Firefox reports an insecure operation on retrieval of the canvas pixel buffer.

> SecurityError: The operation is insecure. Grayscaling_and_inverting_colors:31

The refrenced line is: `var imageData = ctx.getImageData(0, 0, canvas.width, canvas.height);`

> SecurityError: The operation is insecure. A_color_picker:29

The Line is `var pixel = ctx.getImageData(x, y, 1, 1);`

https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Pixel_manipulation_with_canvas

**Comment by chrisdavidmills** [comment] 2020-10-27 13:30
Dupe of https://github.com/mdn/sprints/issues/1127

**Closed by chrisdavidmills** 2020-10-27 13:30 UTC
Labels: Content:WebAPI, Est:Medium, P1
