### ISSUE TITLE
menu problem

### ISSUE THREAD

**Issue by HALLneufmilles** [mdn/sprints#2654] opened 2020-01-05 16:00 UTC
Hello,
Looking at this page for exemple:
https://developer.mozilla.org/fr/docs/Learn/JavaScript/First_steps/What_went_wrong

the link in red color doesn' match withe web page display.

It's difficlte to know where we are in the courses curiculum.

Thanks in advance.

**Comment by peterbe** [comment] 2020-01-06 15:46
The problem is that the links in the sidebar links to the old names. For example, "CSS — Styling the Web" links to `/fr/docs/Learn/CSS` which is a (302) redirect to `/fr/docs/Apprendre/CSS`. 
That's why the Wiki thinks these are new pages that needs to be created. 

That's kinda bad because the system should know that these are not new documents but just "poorly spelled" so that red shouldn't appear.

**Comment by peterbe** [comment] 2020-01-06 15:55
The "immediate" solution is to manually update the sidebar macro so it links the where the redirects are going. But it's a whack-a-mole problem because the new URLs can be rewritten to new ones. 

Remember, in https://github.com/mdn/kuma/pull/6220 we made it so that any `<a href="/exists/not/yet" class="new">` tags get converted to `<a class="new" title="Page has not yet been created.">`. But only for the article content. Clearly not doing it for the sidebar which is a relief here in this context or else all these French sidebars would lack clickable links. 

Also, remember this? https://github.com/mdn/kuma/pull/6219
If the document body has a hyperlink to a relative document but ends with a `/` it essentially says "The author typed the link to `/foo/bar/` but I'm going to assume you meant `/foo/bar` and proceed as normal."

I don't know how feasible it would be to sanitize the sidebar links. There's clearly some code that takes the link `/fr/docs/Learn/CSS`, deconstructs that to `locale="fr" && slug="Learn/CSS"`, learns it doesn't exist spelled like that, and then decides to apply the `class="new"`, which ultimately makes the link appear red as if it's something wrong with it. 

Attention @chrisdavidmills Perhaps you can ponder this and consider how urgent/important this feels and perhaps based on your feeliings we can see if we can do something deep in the kuma wiki machinery.

**Comment by chrisdavidmills** [comment] 2020-01-10 09:43
@peterbe this is a pain. Ultimate the problem is that the sidebars are written assuming that translations will use the same URL paths as the english version, with just translated titles. But different translators do it in different ways, so it is hard to stop this happening.

It would be nice to do something about this, but it ultimately doesn't feel that important compared to all the other things you've got to do. This won't be fixed properly until we have a robust sidebar solution inside the actual platform. Another one for the stumptown pile...

**Comment by peterbe** [comment] 2020-01-10 14:51
Maybe add this to the long list of items that'll get gloriously better when we get a chance to modernize our platform.

**Closed** 2020-05-27 17:49 UTC
