### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension

### ISSUE THREAD

**Issue by Hirnsausen** [mdn/sprints#1319] opened 2019-04-12 03:27 UTC
# Request type

- [x] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [ ] Correction or update

# Details

PAGE:
Your first extension
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension

TEXT:
Create a new directory and navigate to it:
mkdir borderify
cd borderify

PROBLEM:
This page doesn't tell the reader, where to type these two commands. Is it inside the browser's address bar? No one knows, and there seems to be no other page that has that important key information. I want to learn to write extensions, but this missing information makes it impossible, for now.

**Comment by chrisdavidmills** [comment] 2019-04-12 08:08
Duplicate of https://github.com/mdn/sprints/issues/1320

**Closed by chrisdavidmills** 2019-04-12 08:08 UTC
