### ISSUE TITLE
Forced Reflow caused by MozToggler: Create side bar based on HTML5

### ISSUE THREAD

**Issue by atopal** [mdn/sprints#258] opened 2018-07-09 14:28 UTC
Taks:
- [x] reimplemented collapsible side bar using HTML5 instead of JS
- [x] measure and record performance impact

Acceptance Criteria:
- [ ]  side bar doesn't cause recalc and layout
- [x] performance impact reported

**Comment by tkadlec** [comment] 2018-08-29 20:27
Pull requests:
https://github.com/mozilla/kuma/pull/4957
https://github.com/mdn/kumascript/pull/789

**Comment by tkadlec** [comment] 2018-08-29 21:26
Tested on Chrome, 6x CPU throttle.

**Before:**
![screen shot 2018-08-28 at 10 53 47 am](https://user-images.githubusercontent.com/66536/44816542-277a9300-aba8-11e8-9d3b-347d9af94d9f.png)

**After:**
![screen shot 2018-08-28 at 12 06 50 pm](https://user-images.githubusercontent.com/66536/44816560-33665500-aba8-11e8-9820-d5f77d07b828.png)

**Comment by tkadlec** [comment] 2018-08-29 21:28
Only downside is that while we've eliminated the costly toggler functionality, we still use a polyfill for `<details>` that, when testing for browser support, causes a recalc and layout. I'd love to see if we can use a simpler test for support.

The extra work done here is because of a Chrome 10 issue where details was supported, but wouldn't expand. As long as we don't have that kind of issue in any relevant browsers, and as long as the fallback if we do is for the details element to be open, I think would could get away with this extra check.

**Comment by a2sheppy** [comment] 2018-08-30 15:48
Chrome 10 is 7 years old. Do we need to even care about it, really?

**Comment by tkadlec** [comment] 2018-08-30 15:56
I certainly don't think so. :) Hence why I think we should revisit. I think it'd be wise to just do a quick check to confirm there aren't any funky issues like that in anything more recent (I personally haven't tested) before yanking it tho.

**Comment by atopal** [comment] 2018-08-30 17:07
No, we don't have to care about it. @jwhitlock might know about our official support matrix, but Chrome 10 is not on it either way.

**Comment by atopal** [comment] 2018-08-31 14:27
I'm assuming this is a question for @schalkneethling, but I'd do it separately, so we can just roll that one back in case of an issue.

**Comment by jwhitlock** [comment] 2018-09-05 22:06
IE / Edge doesn't have support for ``<details>``/``<summary>`` 😕 

https://developer.microsoft.com/en-us/microsoft-edge/platform/status/detailssummary/

**Comment by ExE-Boss** [comment] 2018-09-05 23:50
Well, we could always load a `<details>`/`<summary>` polyfill for IE / Edge.

**Comment by tkadlec** [comment] 2018-09-05 23:59
We already have a polyfill. I probably wasn't clear enough above, but we'll be keeping it, just simplifying the test that checks if we need to apply it or not.

**Comment by jwhitlock** [comment] 2018-10-02 17:37
One more potential fix in https://github.com/mdn/kumascript/pull/789. We're planning to deploy Thursday, Oct 4, and I'll regenerate pages using the sidebars to apply the change.

**Comment by jwhitlock** [comment] 2018-10-05 14:49
This was deployed yesterday (Oct 4).  I regenerated the 30,954 pages using these sidebars overnight, taking over 13 hours. About 1000 ended up with errors, but these appear to be due to system issues like rate limiting in Bugzilla and network errors, not macro errors.  We should get clean performance numbers starting tomorrow.

**Comment by tkadlec** [comment] 2018-10-05 14:54
>  I regenerated the 30,954 pages using these sidebars overnight, taking over 13 hours.

😱

**Comment by jwhitlock** [comment] 2018-10-05 16:05
To be clear, I have [a script to regenerate pages](https://gist.github.com/jwhitlock/43e34e07bef8c3f1863e91f076778ca6), so my laptop and MDN async workers were doing the work, I just confirmed that we didn't have a repeat of the [broken sidebars on API pages](https://bugzilla.mozilla.org/show_bug.cgi?id=1487640), and slept through most of it. Still, slow rendering is a blocker for our GitHub-based contribution dreams.

@atopal / @tkadlec I think reporting on the real world performance impact is the next action to close this issue.

**Comment by atopal** [comment] 2018-10-05 16:17
We'll probably have that on Monday.

**Comment by atopal** [comment] 2018-10-06 12:12
Looking at Speedcurve, it's a mixed bag, faster on array page, slower on em page. It's really strange, with this change and the previous work the page size is down by 50% in many cases, from 600 to 300kb, and yet, our time to interactive examples has not moved at all. The 90th percentile number went up quite a bit on Friday, but I blame that on invalidating all cached pages at once. Let's see what next week looks like.

**Comment by atopal** [comment] 2018-10-09 14:56
90th percentile on Monday: 4.8s. Median: 1.7s. That's the same a before this went in. And essentially the same numbers we had at the start of August.

**Comment by schalkneethling** [comment] 2018-10-09 14:59
@tkadlec Correct me if I am wrong but, this will mostly give us a perceived performance improvement not so much page load time improvement? Also, seeing that MozToggler is used for the main menu(I believe) perhaps this is still having an affect?

**Comment by tkadlec** [comment] 2018-10-09 15:05
Perceived is certainly a part of it. It should've cleared up some
recalc/layout costs as well, particularly on low powered devices.

**Closed** 2018-10-19 21:06 UTC
