### ISSUE TITLE
 webNavigation API: more transitionTypes in events than documentation reports

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#411] opened 2018-08-10 14:20 UTC
https://bugzilla.mozilla.org/show_bug.cgi?id=1418265

# Acceptance criteria

1. - [ ] Make sure the complete list of transitionType values is supported, as appropriate.

**Comment by irenesmith** [comment] 2018-10-10 12:04
This issue is a duplicate of #[486](https://app.zenhub.com/workspace/o/mdn/sprints/issues/486) which is assigned for Alicia Keyes, Q4, Sprint 1.

**Closed by irenesmith** 2018-10-10 12:04 UTC
