### ISSUE TITLE
Missing Documentation for Upgrade

### ISSUE THREAD

**Issue by mohamedanees6** [mdn/sprints#2186] opened 2019-09-30 15:22 UTC
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [X] New documentation
- [ ] Correction or update

# Details
Documentation of Upgrade is missing

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Upgrade

**Comment by Elchi3** [comment] 2020-05-26 16:17
Duplicate of https://github.com/mdn/sprints/issues/1283

**Closed by Elchi3** 2020-05-26 16:17 UTC
Labels: Content, Content:HTTP, Est:Medium, P2
