### ISSUE TITLE
Geolocation API throwing an error when accepting location access (Firefox)

### ISSUE THREAD

**Issue by Confidenceiskey** [mdn/sprints#1032] opened 2019-02-13 16:31 UTC
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Using Firefox V65.0, I run into a problem on the below link.

[MDN Docs: Geolocation API](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API/#Live_Result)

If you click on the button "show my location", you get the below popup!

<img width="358" alt="image" src="https://user-images.githubusercontent.com/22338256/52724997-c04e7080-2f86-11e9-93e5-a26da8d419c7.png">

When I click on "Allow Location Access", it throws back an error and shows the text "Unable to retrieve your location".

Upon deeper inspection, it has an error code of 1. The error message given is "User denied geolocation prompt", which is clearly NOT true at all. 

[Here is a working codepen link](https://codepen.io/Confidenceiskey/pen/exjLZB) that shows the above error messages.

Not sure how to fix, but there appears to be a bug with allowing location access using Firefox. It works fine on Chrome.

**Comment by jwhitlock** [comment] 2019-02-15 20:50
I got a similar result the first time I tried this, but on a second try the example works for me on FF 66 (Dev Edition) on:

* MDN: https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API#Live_Result
* When clicking "Open in CodePen" from MDN
* [Your codepen](https://codepen.io/Confidenceiskey/pen/exjLZB)

I suspect this is a bug with the Geolocation component, which has [58 open bugs](https://bugzilla.mozilla.org/buglist.cgi?product=Core&component=Geolocation&resolution=---&list_id=14569393). It makes some sense to me that the Geolocation service would not work on the first try for a laptop, which probably uses an IP-to-location service that may not respond within a timeout. Peaking at ``about:config``, it looks like FF 66 uses Google's geolocation API.

Others who test this issue - please be prepared to record the error state on the first call

**Comment by chrisdavidmills** [comment] 2019-02-21 16:52
Looks like a Firefox bug; we'll close this and file a bug on bugzilla.

**Closed by chrisdavidmills** 2019-02-21 16:52 UTC
Labels: Content, P2

**Comment by Nashorn** [comment] 2019-05-31 11:47
Any update on this? Opening an html file:/ on disk (not localhost) and i get the error.

**Comment by p810** [comment] 2019-08-01 20:04
I think this bug is affecting my team as well. We're getting the same `PositionError` when calling `Geolocation.getCurrentPosition()`. I verified that this isn't related to the module we're testing by calling the method in dev tools and clicking "Allow Location Access."

The above link to the bug tracker is showing an empty result set - I think the component may have been renamed because I can't find "Geolocation" in the component list on the search page.

**Comment by p810** [comment] 2019-08-01 20:33
I checked out the issue referenced above and a user named [moklick posted the solution](https://github.com/FixMyBerlin/fixmy.frontend/issues/13#issuecomment-501207171). Turns out this is not a bug with Firefox, but a feature of MacOS. To fix it, you just need to go into System Preferences > Security & Privacy > Privacy, check "Enable Location Services," and specify Firefox as one of the apps that's allowed access.

I don't know exactly why Chrome _wasn't_ having this problem, but I imagine it might be falling back to a less accurate means of locating the user (IP based?), because I did notice a difference of ~25% in the accuracy between Chrome and Firefox. 

GeoIP might be one way to alleviate this for MacOS FF users, or you could prompt them to enable Location Services. But it's hard to tell since the user may have denied the page the right to their location. I wonder if a feature request or bug report should be opened to implement something similar to Google's fallback, or a better error message? The latter may not be possible since it might break from the Geolocation spec, but returning a `PositionError` when the user intended to share their location feels wrong.

**Comment by Nashorn** [comment] 2019-08-01 20:39
I'll have to test that out. I ended up getting FF60 and it works. Anything higher won't allow geolocation testing on localhost.

**Comment by Nashorn** [comment] 2019-08-02 11:33
@p810 -- Confirmed. That fix works. Geolocation working locally on FF68 now.
Thanks!
