### ISSUE TITLE
Q3 S1 Fx62 WebExt DDNs

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#251] opened 2018-06-28 16:28 UTC
## Acceptance criteria

- [x] Changes made to fix all DDNs
- [x] Reviews requested from engineers
- [x] Release notes updated

## Will

- [x] [Web extensions: SSL (TLS) status API request](https://bugzilla.mozilla.org/show_bug.cgi?id=1322748) 2 points
- [x] [Expose API to customize where new tabs open](https://bugzilla.mozilla.org/show_bug.cgi?id=1344749) 0.25 points
- [x] [Remove support for unpacked side-loaded extensions](https://bugzilla.mozilla.org/show_bug.cgi?id=1385057) 0.5 points

## Irene

- [x] [deprecate windowTypes for windows.get, windows.getCurrent and windows.getLastFocused](https://bugzilla.mozilla.org/show_bug.cgi?id=1419132) 0.25 points
- [x] [webRequest.onBeforeRequest fetch redirect gets blocked due to bogus CORS error](https://bugzilla.mozilla.org/show_bug.cgi?id=1450965) 0.5 points BUG NOT YET RESOLVED; NO WORK TO DO YET ON THIS ONE
- [x] [Consider allowing to modify browserAction per window](https://bugzilla.mozilla.org/show_bug.cgi?id=1419893) 0.5 points
- [x] [Reconsider opening sidebar on install of an extension](https://bugzilla.mozilla.org/show_bug.cgi?id=1460910) 0.25 points
- [x] [Allow changing the tab separator color](https://bugzilla.mozilla.org/show_bug.cgi?id=1459455): 0 points, Irene already did this, just waiting for review.
- [x] [remove browser_style warnings](https://bugzilla.mozilla.org/show_bug.cgi?id=1404724) 0.25 points
- [x] [Change nsIContentPolicy shouldLoad to take an nsILoadInfo instead of the various arguments](https://bugzilla.mozilla.org/show_bug.cgi?id=1439713) 0 points, not a WE bug

**Comment by jmswisher** [comment] 2018-07-20 19:57
@chrisdavidmills, @atopal Can this issue be closed?

**Comment by chrisdavidmills** [comment] 2018-07-23 07:40
Yes, closing.

**Comment by irenesmith** [comment] 2018-07-24 12:01
[1460910](https://bugzilla.mozilla.org/show_bug.cgi?id=1460910) - Added open_at_install to the sidebar_action manifest key. Release notes updated.

**Comment by irenesmith** [comment] 2018-07-25 12:15
[1450965](https://bugzilla.mozilla.org/show_bug.cgi?id=1450965) -- No work to be done yet because the issue has not been resolved.

**Comment by irenesmith** [comment] 2018-07-27 20:32
[1419893](https://bugzilla.mozilla.org/show_bug.cgi?id=1419893) This is the only remaining issue for this task. I have requested more information for resolving this and will update on Monday morning.

**Comment by irenesmith** [comment] 2018-08-02 11:54
The methods that need to be changed are
[1419893](https://bugzilla.mozilla.org/show_bug.cgi?id=1419893) - Consider allowing to modify browserAction per window. The methods that need to be changed are:
- [ ] browserAction.setTitle
- [ ] browserAction.getTitle
- [ ] browserAction.setIcon
- [ ] browserAction.setPopup
- [ ] browserAction.getPopup
- [ ] browserAction.setBadgeText
- [ ] browserAction.getBadgeText
- [ ] browserAction.setBadgeBackgroundColor
- [ ] browserAction.getBadgeBackgroundColor
- [ ] browserAction.isEnabled

**Comment by irenesmith** [comment] 2018-08-07 15:26
[setTitle](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserAction/setTitle)
[getTitle](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserAction/getTitle)
[setIcon](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserAction/setIcon)
[setPopup](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserAction/setPopup)
[getPopup](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserAction/getPopup)
[setBadgeText](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserAction/setBadgeText)
[getBadgeText](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserAction/getBadgeText)
[setBadgeBackgroundColor](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserAction/setBadgeBackgroundColor)
[getBadgeBackgroundColor](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserAction/getBadgeBackgroundColor)
[isEnabled](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserAction/isEnabled)

**Comment by irenesmith** [comment] 2018-08-07 18:33
The changes for [1419893](https://bugzilla.mozilla.org/show_bug.cgi?id=1419893) have been reviewed and the issue is now dev-tools-complete

**Closed by irenesmith** 2018-08-07 18:33 UTC
Labels: Cf:High
