### ISSUE TITLE
/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find

### ISSUE THREAD

**Issue by SatheesA** [mdn/sprints#2912] opened 2020-03-06 11:14 UTC
# Request type
- [x ] Correction or update

# Details
the formatting on the example is wrong
![image](https://user-images.githubusercontent.com/4419762/76078902-e1c03700-5fa3-11ea-9be5-9e884de8e7de.png)

There is no margin between the line numbers and the content in the first example called JavaScript Demo: Array.find()

**Comment by chrisdavidmills** [comment] 2020-03-06 11:37
@peterbe @tobinmori @schalkneethling @wbamberg  FYI that this is still happening. I know that this is a known issue so I'll close it, but I wasn't sure where this is being tracked, so can you link it to the issue it is a dupe of? Thanks.

**Closed by chrisdavidmills** 2020-03-06 11:37 UTC

**Comment by peterbe** [comment] 2020-03-06 15:04
I have some mental plans how to fix it but none of them are low-hanging. I don't want to have to keep trying to patch `bob` any further. We 
The best thing to do would be to rewrite it into Yari 2.
