### ISSUE TITLE
https://wiki.developer.mozilla.org/en-US/docs/MDN/Feedback

### ISSUE THREAD

**Issue by CptAwe** [mdn/sprints#3003] opened 2020-03-30 01:55 UTC
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
In the [contentScripts docs](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/contentScripts) the link to the example should be updated. At the moment it points to a [404](https://github.com/mdn/webextensions-examples/tree/master/user-script) on GitHub. I suggest to point to [user-script-register](https://github.com/mdn/webextensions-examples/tree/master/user-script-register).

**Comment by chrisdavidmills** [comment] 2020-03-30 08:43
@rebloor I don't suppose you've got a little bit of time to try to figure out how this works? Actually @wbamberg write these macros originally, so can probably save us some time.

**Comment by rebloor** [comment] 2020-03-30 09:33
@chrisdavidmills I believe I know what the issue is, l'll fix this tomorrow

**Comment by wbamberg** [comment] 2020-03-31 02:43
It just needed a page refresh, should be working now.

**Comment by chrisdavidmills** [comment] 2020-03-31 06:36
@wbamberg ah, thanks Will ;-)

So we can close this now then.

**Closed by chrisdavidmills** 2020-03-31 06:36 UTC
Labels: Content, Content:WebExt, Est:Small, P1
