### ISSUE TITLE
Provide information on what ES version a JS feature is added in

### ISSUE THREAD

**Issue by MichaelOdumosu57** [mdn/sprints#1682] opened 2019-05-30 02:55 UTC
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [ ] Correction or update

# Details

 Correction or update

when im learning about items in javascript, closures ternary operators higher order methods for functions and the sort i dont know what ecmascript version they are es5 es6 eslint and so i, i need this in the specs because this is crucial to my API projects thanks much MDN the best

for now since i think of using closures, tell me is clousres in the use of

function Foo(bar){
     var _name = bar
     function getName(){return _name}
}
is es5 javascript

and fix the global larger problem thanks much MDN the best

**Comment by Elchi3** [comment] 2020-05-20 16:45
Duplicate of https://github.com/mdn/sprints/issues/2735

**Closed by Elchi3** 2020-05-20 16:45 UTC
