### ISSUE TITLE
/zh-CN/docs/Web/HTTP/Access_control_CORS

### ISSUE THREAD

**Issue by Wana-Fly-Boy** [mdn/sprints#2447] opened 2019-11-23 10:53 UTC
预检请求的案例中自定义字段Content-Type是application/xml，还是text/xml？内容表述有歧义。

**Comment by chrisdavidmills** [comment] 2019-11-25 14:24
I think this bit on the English version answers your question:

https://wiki.developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Preflighted_requests

Looks like it is `application/xml`. Are you OK to update the Chinese version to make this clearer?

**Comment by Wana-Fly-Boy** [comment] 2019-11-26 03:24
There is a problem with the preflight request example in the English version, the text and code section is "application / xml", and the picture is "text / xml".

**Comment by Wana-Fly-Boy** [comment] 2019-11-26 03:26
The request header field of the code part is "Ping-Other", but the text part and the picture are "X-PINGOHTHER".

**Comment by Elchi3** [comment] 2020-05-27 14:54
Duplicate of https://github.com/mdn/sprints/issues/2487

**Closed by Elchi3** 2020-05-27 14:54 UTC
Labels: Content, Content:HTTP, Est:Small, P2
