### ISSUE TITLE
Remote debugging docs tasks for Fx68

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1574] opened 2019-05-16 18:30 UTC
See https://trello.com/c/ZLneh5mV/10-new-remote-debugging-aboutdebugging-fx-68 for original trello card

# Acceptance criteria

1. - [ ] [[remote-dbg-next] about:debugging lists search webextensions by default](https://bugzilla.mozilla.org/show_bug.cgi?id=1544372) — documented appropriately.

**Comment by irenesmith** [comment] 2019-05-23 11:59
Closing this as a duplicate of [Sprints #1392](https://app.zenhub.com/workspace/o/mdn/sprints/issues/1392)

**Closed by irenesmith** 2019-05-23 11:59 UTC
Labels: Cf:High, Content, Content:DevTools, Firefox68
