### ISSUE TITLE
Pages for WebExtensions are forwareded to extensionworkshop.com ignoring translation under MDN 

### ISSUE THREAD

**Issue by hmatrjp** [mdn/sprints#3272] opened 2020-05-23 09:27 UTC
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Some pages under https://wiki.developer.mozilla.org/ja/docs/Mozilla/Add-ons/WebExtensions/ are forwarded to under corresponding pages in extensionworkshop.com .
It is inconvenient for Japanese readers, while extensionworkshop.com does not provide the space and mean to put its translated contents.

Following is the list of the pages forwarded under webextensions.com. 
I found them in the section 
https://wiki.developer.mozilla.org/ja/docs/Mozilla/Add-ons/WebExtensions#Firefox_workflow
and around.

https://wiki.developer.mozilla.org/ja/docs/Mozilla/Add-ons/WebExtensions/Security_best_practices
https://wiki.developer.mozilla.org/ja/docs/Mozilla/Add-ons/WebExtensions/Porting_a_legacy_Firefox_add-on
https://wiki.developer.mozilla.org/ja/docs/Mozilla/Add-ons/WebExtensions/Developing_WebExtensions_for_Firefox_for_Android
https://wiki.developer.mozilla.org/ja/docs/Mozilla/Add-ons/WebExtensions/Comparison_with_the_Add-on_SDK
https://wiki.developer.mozilla.org/ja/docs/Mozilla/Add-ons/WebExtensions/Comparison_with_XUL_XPCOM_extensions
https://wiki.developer.mozilla.org/ja/docs/Mozilla/Add-ons/WebExtensions/Differences_between_desktop_and_Android
https://wiki.developer.mozilla.org/ja/docs/Mozilla/Add-ons/WebExtensions/User_experience_best_practices
https://wiki.developer.mozilla.org/ja/docs/Mozilla/Add-ons/WebExtensions/Temporary_Installation_in_Firefox
https://wiki.developer.mozilla.org/ja/docs/Mozilla/Add-ons/WebExtensions/Debugging
https://wiki.developer.mozilla.org/ja/docs/Mozilla/Add-ons/WebExtensions/Testing_persistent_and_restart_features
https://wiki.developer.mozilla.org/ja/docs/Mozilla/Add-ons/WebExtensions/Getting_started_with_web-ext
https://wiki.developer.mozilla.org/ja/docs/Mozilla/Add-ons/WebExtensions/web-ext_command_reference
https://wiki.developer.mozilla.org/ja/docs/Mozilla/Add-ons/WebExtensions/WebExtensions_and_the_Add-on_ID
https://wiki.developer.mozilla.org/ja/docs/Mozilla/Add-ons/WebExtensions/Distribution_options
https://wiki.developer.mozilla.org/ja/docs/Mozilla/Add-ons/WebExtensions/Request_the_right_permissions
https://wiki.developer.mozilla.org/ja/docs/Mozilla/Add-ons/WebExtensions/Retiring_your_extension
https://wiki.developer.mozilla.org/ja/docs/Mozilla/Add-ons/WebExtensions/Development_Tools

..... There may be more.

**Comment by caitmuenster** [comment] 2020-05-29 16:40
Hi @hmatrjp, thank you for filing this issue. We need to implement localization tooling for Extension Workshop to restore translated text; this issue is filed at https://github.com/mozilla/extension-workshop/issues/51. 

I am really sorry for the inconvenience and I hope we can fix this soon.

**Comment by Elchi3** [comment] 2020-06-01 12:11
Closing as duplicate of https://github.com/mozilla/extension-workshop/issues/51

**Closed by Elchi3** 2020-06-01 12:11 UTC
Labels: Content:WebExt
