### ISSUE TITLE
https://developer.mozilla.org/ru/docs/Web/JavaScript/JavaScript_technologies_overview

### ISSUE THREAD

**Issue by BechMan** [mdn/sprints#1487] opened 2019-05-05 22:26 UTC
# Request type
- [ ] Correction or update

# Details
The page (https://developer.mozilla.org/ru/docs/Web/JavaScript/JavaScript_technologies_overview) at the end refers to the common library prototypejs, which died in 2015

**Comment by chrisdavidmills** [comment] 2019-05-08 16:00
Closing; duplicate of https://github.com/mdn/sprints/issues/1486

**Closed by chrisdavidmills** 2019-05-08 16:00 UTC
