### ISSUE TITLE
The performance hazards of [[Prototype]] mutation

### ISSUE THREAD

**Issue by SoftMoonWebWare** [mdn/sprints#2877] opened 2020-02-28 17:58 UTC
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [] New documentation
- [x] Correction or update

# Details
I realize the page is incomplete (and not updated for the past year).
If I read and understand this topic correctly (which I think I might just barely be able to do), I come to the conclusion that if you are going to mutate a [[Prototype]], it would be best to do so at the onset of all scripts running/compiling; I am guessing that if script[0] (be it a linked file or an inline script tag) initially modified something as drastic as Element.prototype, then script[1] and script[2], etc. would optimize quite well .  Then they would be more optimized as the JIT compiler takes the mutation further into account.  Contrast that with mutating an object that has already lived for a while, and been passed around for a while.
It would be nice to have this conclusion verified in this article:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/The_performance_hazards_of__[[Prototype]]_mutation

Also, this issue popped up for me as "related", so what gives?  That "seems" to disqualify the entire argument in this topic issue, but I think that would depend on the code set he was running, as it relates to the topic of this issue.
Inaccurate warnings related to setting/getting [[Prototype]] #993
https://github.com/mdn/sprints/issues/993

Thanks for your time and this wonderful programming language.  I like it!

**Comment by Elchi3** [comment] 2020-05-20 14:06
I think this issue is a duplicate of #993. We should try again to contact the author and finish this page.

**Closed by Elchi3** 2020-05-20 14:06 UTC
Labels: Content, Content:JS, Est:Medium, P2
