### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver

### ISSUE THREAD

**Issue by ethanmills** [mdn/sprints#3798] opened 2020-10-15 16:58 UTC
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The example for [ResizeObserver ](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver/ResizeObserver) does not work on Chrome  86.0.4240.75. It uses `entry.contentBoxSize.inlineSize`, where as it should be `entry.contentBoxSize[0].inlineSize` on Chrome. From a brief look at the draft specification, it seems that the fact it works on Firefox is a bug with the Firefox implementation, since contentBoxSize should be `FrozenArray<ResizeObserverSize>`.

https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver
https://mdn.github.io/dom-examples/resize-observer/resize-observer-text.html
https://github.com/mdn/dom-examples/blob/master/resize-observer/resize-observer-text.html
https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver/ResizeObserver
https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver/observe
https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver/unobserve

**Comment by Rumyra** [comment] 2020-11-11 13:47
This is partly a duplicate of https://github.com/mdn/sprints/issues/3823

List of docs checked

- [ ] https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver
- [ ] https://mdn.github.io/dom-examples/resize-observer/resize-observer-text.html
- [ ] https://github.com/mdn/dom-examples/blob/master/resize-observer/resize-observer-text.html
- [ ] https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver/ResizeObserver
- [ ] https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver/observe
- [ ] https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver/unobserve

**Closed** 2021-01-20 08:41 UTC
Labels: 1 hour task, Content:WebAPI
