### ISSUE TITLE
Examples don't work at all

### ISSUE THREAD

**Issue by North46** [mdn/sprints#2376] opened 2019-11-05 15:53 UTC
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x ] Correction or update

# Details

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Auto-placement_in_CSS_Grid_Layout

The page above provides a number of examples of auto-placement in CSS Grid Layout.  The examples can been viewed in either CodePen or JSFiddle.  Clicking on those links opens up the examples, but none of them format correctly.  I'm still trying to learn CSS and auto-placement, so I can't pinpoint the problem.

**Comment by Leokuma** [comment] 2019-11-09 02:22
You're right.

The problem is that the CSS code in Codepen and JSFiddle is very different from the one at MDN. The snippet must be updated in both websites.

**Comment by SphinxKnight** [comment] 2019-11-13 09:50
There is a bug in the "macro" that generates the code for CodePen / JSFiddle because some parts of the code are hidden.
@North46 , I think I'll remove the hidden attribute so that such confusion may be avoided.
In the meantime, you can look at those "hidden" fragments in the editing mode: https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Auto-placement_in_CSS_Grid_Layout$edit 
I know it's just a workaround but I hope it'll help in the meantime

**Comment by North46** [comment] 2019-11-13 18:53
Thanks for following up on this.  I found the answer I was looking for, but it would be helpful to fix it for the next person who tries to learn from it.

**Comment by SphinxKnight** [comment] 2019-12-16 07:24
Hello again @North46, this has been fixed with #6161. I have tested on the page you provided and it looks ok to me now. I'll close this one but feel free to reopen it if you cannot confirm on your end.

**Closed by SphinxKnight** 2019-12-16 07:24 UTC

**Comment by North46** [comment] 2019-12-16 19:50
Looks great - thanks!!
