### ISSUE TITLE
As a PM I want to welcome users with an email optimized for them, so they have a CTA to get started

### ISSUE THREAD

**Issue by atopal** [mdn/sprints#2498] opened 2019-11-27 14:05 UTC
This will largely be a textual change to the email, so that it's targeted towards ALL MDN users (not Contributors only as it is now).

@atopal will provide text for this.

**Comment by jmswisher** [comment] 2019-12-05 17:03
Duplicate of #2425

**Closed by jmswisher** 2019-12-05 17:03 UTC
Labels: KR: Membership Accts
