### ISSUE TITLE
U — write report detailing FED learning pathway followups.

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#3295] opened 2020-05-27 18:46 UTC
We need a report detailing followup work to be done on the FED learning pathway, along with detailed breakdown, milestones/deliverables, schedule, and required resources.

# Acceptance criteria

- [x] Report written

**Comment by Elchi3** [comment] 2020-06-02 14:22
Dupe of https://github.com/mdn/sprints/issues/3145

**Comment by chrisdavidmills** [comment] 2020-07-22 14:46
Report available at https://docs.google.com/document/d/1v_10rfJOQhBUFzhAjsaPUQHmr5oRVU5tS7TbNpr46So/edit#heading=h.qwycjiweuztn

**Closed** 2020-08-02 12:05 UTC
Labels: Cf:High, Content:Learn
