### ISSUE TITLE
bug 1519582: Bleach content when saving revisions

### ISSUE THREAD

**Issue by jwhitlock** [mdn/sprints#936] opened 2019-02-05 21:40 UTC
# User story
As an editor, I want bleaching and normalization on current and new revisions, to reduce the differences between revisions and published content.

# Acceptance criteria
* Revisions are "bleached" on save:
  - Forbidden elements and attributes are removed
  - Attribute order is normalized
  - Section heading get content-based IDs
* (Optional) Return to editor if bleaching changed the content
* Process the current revisions to apply bleaching, preferably with a "robot" revision

# References
* [bug 1519582](https://bugzilla.mozilla.org/show_bug.cgi?id=1519582) - Update wiki.document_api (API) to use the content of the document's current revision
* [Rendering details](https://kuma.readthedocs.io/en/latest/rendering.html)

**Comment by escattone** [comment] 2019-03-12 00:03
see https://github.com/mozilla/kuma/pull/5294

**Comment by escattone** [comment] 2019-03-19 20:40
PR mozilla/kuma#5294 was deployed to production on Monday, March 18, and I ran the `kc exec -it <web-pod> ./manage.py clean_document --all` command (cleans the current revision of all documents) on the production DB starting around 4:30pm PT on the same day.

The `mdn-dev@mozilla.com` email group received a few hundred emails reporting errors like this:
```
Subject: [mdn] Error while cleaning document 232521
Body: (1062, "Duplicate entry 'Web/API/PaymentRequest/PaymentRequest.onmerchantvalidation-en-US' for key 'wiki_document_slug_68e6ba482859eef0_uniq'")
```
during the cleaning step. From a few samples I looked into, they seem to have occurred on documents that were content-based redirects, which don't need to be cleaned, but I'm not sure what happened. It seems that the only way this could occur is if the slug of the new revision was different than the slug of the document (which could likely trigger the unique constraint `wiki_document_slug_68e6ba482859eef0_uniq` that exists on the `wiki_document` table during the `rev.make_current()` call), but in the few cases I checked, that was not the case.

**Comment by escattone** [comment] 2019-03-22 16:48
### Incomplete first run
It appears that the `kc exec -it <web-pod> ./manage.py clean_document --all` command I ran on Monday only completed a portion of the total number of documents, and that portion is probably less than 20% since I didn't receive any progress emails (which are sent after each chunk of 20% completes). 😞 I'll need to re-run at an appropriate time, but also make an adjustment to the code (see below).

### The reason for the `Error while cleaning document` errors
I have more insight into the emails sent to mdn-dev@mozilla.com reporting errors like this:
```
Subject: [mdn] Error while cleaning document 232521
Body: (1062, "Duplicate entry 'Web/API/PaymentRequest/PaymentRequest.onmerchantvalidation-en-US' for key 'wiki_document_slug_68e6ba482859eef0_uniq'")
```
My guess in the comment above was correct. This error occurs because the slug of the document is different than the slug of its current revision. My mistake in the comment above was to look at the document of the redirect, instead of the document reporting the error (which was the document with pk=232521). The document that generates the error during cleaning is the document being redirected to, and I see that the slug of its current revision is different than the slug of the document (the slug of the current revision has the slug of the redirected document):
```python
>>> doc = Document.objects.get(pk=232521)
>>> doc.slug
u'Web/API/PaymentRequest/onmerchantvalidation'
>>> doc.current_revision.slug
u'Web/API/PaymentRequest/PaymentRequest.onmerchantvalidation'
```

**Comment by jmswisher** [comment] 2019-04-29 19:30
@escattone Can this be closed? IIRC you fixed the initial problem with the bot.

**Comment by escattone** [comment] 2019-04-29 20:53
@jmswisher Thanks for catching that I had not yet closed this. I had closed the bugzilla bug but forgot about this. I'm including below my final notes:

PR https://github.com/mozilla/kuma/pull/5294 was deployed to production. All content (e.g., the content arriving from CKEditor) is cleaned before saving it on a new revision. I ran a Django management command (`./manage.py clean_document --all`) that cleaned the current revision of every document, and then saved it as the new current revision (but only if the document had a current revision and the content of that current revision changed when cleaned). These two steps unlocked clean diffs when using GET/PUT on the `$api` endpoint. Will Bamberg made some changes via the `$api` endpoint and confirmed to me via email (over the weekend from Friday March 29 through Sunday March 31st) that the resulting diffs were clean and what he expected to see. So this has been resolved since about 19 days ago.

By the way, the cleaning process consists of these steps:
- bleaching (e.g., elements and attributes not included within the whitelisted ones are removed, like the `onclick` attribute)
- section `id`'s are added to all `h1`-`h5` elements
- attributes are ordered alphabetically
- non-whitelisted sources for `iframe` elements are stripped

**Closed by escattone** 2019-04-29 20:53 UTC
Labels: Cf:Low
