### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Pixel_manipulation_with_canvas

### ISSUE THREAD

**Issue by oea-san** [mdn/sprints#3548] opened 2020-07-28 10:21 UTC
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [] New documentation
- [x] Correction or update

The canvas image is tainted so the examples break. The screenshot says it all I think. The first and second hippo have this problem, the third got lucky.

![Screen Shot 2020-07-28 at 12 17 14](https://user-images.githubusercontent.com/10627810/88653659-a518e780-d0cc-11ea-9840-e5555eb29e5d.png)

# Details

https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Pixel_manipulation_with_canvas

**Comment by gsouquet** [comment] 2020-10-22 21:40
I have updated the examples and asked for a technical review 👍

**Comment by chrisdavidmills** [comment] 2020-10-27 13:30
Dupe of https://github.com/mdn/sprints/issues/1127

**Closed by chrisdavidmills** 2020-10-27 13:30 UTC
Labels: 1 hour task, Content:WebAPI
