### ISSUE TITLE
https://wiki.developer.mozilla.org/es/docs/Learn/Herramientas_y_pruebas/Lado-del-cliente_JavaScript_frameworks

### ISSUE THREAD

**Issue by spaceinvadev** [mdn/sprints#3627] opened 2020-08-22 23:03 UTC
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x ] Correction or update

# Details
The "Svelte Tutorial" section is missing when translating the page into Spanish.

![image](https://user-images.githubusercontent.com/49292621/90967203-62ff7d80-e4a1-11ea-9a8b-aa1e82a27249.png)

I fully translated the page into Spanish but I couldn't get the missing section to be displayed in the "Edit" view. It was already missing when I started the translation. Now the page in its Spanish version has no "Svelte Tutorial" section.

Please add it, or have it available so I can translate it.

**Comment by chrisdavidmills** [comment] 2020-09-28 14:56
I don't really understand what the problem is here. When you edit the translation, the Svelte section is available to be translated on the left-hand side. It is a pretty recent addition, so maybe it took a while for that view to be updated?

I'm closing this now. Please let me know if you still have an issue here.

**Closed by chrisdavidmills** 2020-09-28 14:56 UTC
