### ISSUE TITLE
Proxy settings

### ISSUE THREAD

**Issue by pispox** [mdn/sprints#4016] opened 2021-11-28 12:17 UTC
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [ ] Correction or update

# Details

When you set proxy in private browsing it changes in normal configuration too.

**Comment by hamishwillee** [comment] 2021-11-28 23:33
@pispox We need some more details on the intent here. Do you have a page, and section that you would like updated - or some specific text that is incorrect? Please provide links and screenshots here so we can find it and make any needed updates.

**Comment by caugner** [comment] 2023-10-10 11:54
Closing as the issue is missing important details to act upon.

**Closed by caugner** 2023-10-10 11:54 UTC
Labels: needs triage
