### ISSUE TITLE
WebExt Storage API docs tasks for Fx 68

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1577] opened 2019-05-17 10:32 UTC
See https://trello.com/c/Pw66h6fb/56-storage-api-related-tasks-fx-68 for original trello card.

# Acceptance criteria

1. - [ ] [Implement "chrome.storage.managed"](https://bugzilla.mozilla.org/show_bug.cgi?id=1230802) — documented appropriately.

**Comment by irenesmith** [comment] 2019-05-23 12:26
Closing because this is a duplicate of: [Sprints #1430](https://app.zenhub.com/workspaces/mdn-sprint-board-5ab3d23fd0f4ea53b0022a61/issues/mdn/sprints/1430) for Firefox 67. From what I see, this is a 67 issue.

**Closed by irenesmith** 2019-05-23 12:26 UTC
Labels: Cf:High, Content, Content:WebExt, Firefox68
