### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/MDN/Feedback

### ISSUE THREAD

**Issue by ALindsayH** [mdn/sprints#1362] opened 2019-04-19 05:37 UTC
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [ ] Correction or update

# Details

I'm trying to learn more about CSS Grid and I found the excellent document entitled "Box alignment in CSS Grid Layout" and proceeded to replicate the examples within. For the most part, I achieved the desired result but in "Aligning the grid tracks on the block axis", I failed. My result 
has items 3 and 4 occupying the full height of row 3 instead of the expected result of occupying only the top half of row 3. As I have used the sample code, I'm confused about the result.

Regards, Alan.
![sample](https://user-images.githubusercontent.com/2783964/56408614-aac43280-62b8-11e9-8b57-369b178943d9.gif)

**Comment by rachelandrew** [comment] 2020-10-30 13:08
Hi @ALindsayH - can I see the code you used? The demos have live code and seem to be doing what they say they do. I'd need to se your code to be able to see what you have done differently.

**Comment by ALindsayH** [comment] 2020-10-30 22:24
Rachel, I’ve got a few different things going on, can you remind me what
demos you are talking about?

Alan.

**Comment by rachelandrew** [comment] 2020-10-31 09:09
@ALindsayH you said you were looking at this page https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Box_Alignment_in_CSS_Grid_Layout but that your example didn't work as expected. If there is something unclear on the page that led you to raise the issue, I'd like to fix it but without seeing your code I can't tell.

**Comment by ALindsayH** [comment] 2020-10-31 11:25
Was my question or comment recent because I did not think I had done
serious work with CSS for some years?

Alan.

**Comment by rachelandrew** [comment] 2020-12-02 14:05
@chrisdavidmills this is a very old issue, which I can't see where the problem is and it has been some time since the OP has done any CSS.

**Comment by chrisdavidmills** [comment] 2020-12-02 14:29
@rachelandrew no worries, let's close this one then.

**Closed by chrisdavidmills** 2020-12-02 14:29 UTC
Labels: Content:CSS, Est:Small, P2
