### ISSUE TITLE
Cross-origin taint error on canvas example

### ISSUE THREAD

**Issue by groda** [mdn/sprints#1127] opened 2019-03-01 08:31 UTC
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The demos at [https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Pixel_manipulation_with_canvas](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Pixel_manipulation_with_canvas#Grayscaling_and_inverting_colors) give cross-origin errors (on Chrome):
`Uncaught DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data.
    at draw (pen.js:26:23)
    at Image.img.onload (pen.js:18:3)`

I was able to run them using imgur.com with `img.crossOrigin = ""` see [https://codepen.io/anon/pen/ZPQyqK](https://codepen.io/anon/pen/ZPQyqK)

**Comment by chrisdavidmills** [comment] 2019-03-06 16:51
Similar problem before was fixed by hosting example on GitHub instead of MDN live example.

**Comment by wbamberg** [comment] 2019-03-06 16:53
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1501297 and https://github.com/mdn/dom-examples/pull/29.

**Comment by wbamberg** [comment] 2019-11-20 19:39
> Similar problem before was fixed by hosting example on GitHub instead of MDN live example.

Thinking again, that was a bit different. That was to get an example to work on an MDN page. If I understand this issue, the examples in https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Pixel_manipulation_with_canvas#Grayscaling_and_inverting_colors work fine in the page, but they don't work if you click the "Open in CodePen" button, because the image and the code are then cross-origin.

As @groda says, it does work if you serve images from imgur.com *and* set the `crossorigin` attribute to `""` (or `anonymous`, [which is the same thing](https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_settings_attributes)).

But you can't just fix this in the example, you need the server to cooperate. So it works with imgur.com because that site sends the  [Access-Control-Allow-Origin: *](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin) header. But it won't work with files served from https://mdn.mozillademos.org/, because we don't set that header.

I don't think we want to keep our media at imgur.com. But it looks like https://mdn.github.io/ *does* include the cross-origin header (https://wiki.developer.mozilla.org/en-US/docs/User:wbamberg/test-cross-origin). So it looks like we could fix this by keeping the hippo on GitHub.

**Comment by gsouquet** [comment] 2020-10-23 08:43
This looks like a duplicate of #3548 

I have "fixed" the issue by adding `crossorigin="anonymous"` to the images. However I was not aware of the codepen/JSFiddle feature up until seeing that comment.

Looking at the comment above it seems that https://mdn.github.io/ is not a thing anymore. Happy to update the example further and keep the hippo in a place where more lax CORS header are set

**Comment by chrisdavidmills** [comment] 2020-10-23 08:53
Hi @gsouquet !

We do have live examples at https://mdn.github.io, just not at the root. For example, https://mdn.github.io/dom-examples/

I think the best thing to do here would be to create a new directory inside https://github.com/mdn/dom-examples for all the 2d canvas examples, then put this example inside there, and embed it using the `{{EmbedGHLiveSample()}}` macro (see [here](https://wiki.developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Grid_skills) for a usage example).

Would you have any time to help me with this particular issue? For example, if you filed a PR for the new example on GitHub, I could update the macro calls, or whatever.

**Comment by gsouquet** [comment] 2020-10-23 08:55
Sounds great! Happy to take this task on
Thank you for the pointers, I'll sort it out this week-end

**Comment by chrisdavidmills** [comment] 2020-10-23 09:01
That's awesome, thanks @gsouquet . Feel free to ping me for a review.

**Comment by gsouquet** [comment] 2020-10-27 11:11
I'm managed to move the example to the DOM examples repo

@chrisdavidmills could you review the following please

- [ ] Review and merge mdn/dom-examples#67
- [ ] Close duplicate issues #3548 and #3208 

Tasks for me once the PR has been merged

- [ ] Update color picker example `{{EmbedGHLiveSample("dom-examples/canvas/pixel-manipulation/color-picker.html", '100%', 250)}}`
- [ ] Update color manipulation example `{{EmbedGHLiveSample("dom-examples/canvas/pixel-manipulation/color-manipulation.html", '100%', 250)}}`
- [ ] Update image smoothing example `{{EmbedGHLiveSample("dom-examples/canvas/pixel-manipulation/image-smoothing.html", '100%', 250)}}`

**Comment by chrisdavidmills** [comment] 2020-10-27 13:31
Example reviewed, dupes closed.

**Comment by gsouquet** [comment] 2020-10-29 10:30
Thank you @chrisdavidmills.
Page updated, we can mark this task as completed and close this issue ✅

**Comment by chrisdavidmills** [comment] 2020-10-29 10:53
Awesome, I agree that this can be closed now. I just made a couple of small tweaks, and added in links to the full source code because I thought they'd be useful.

**Closed by chrisdavidmills** 2020-10-29 10:53 UTC
Labels: Content:WebAPI, Est:Medium, P2
