### ISSUE TITLE
Browser version dates, please

### ISSUE THREAD

**Issue by jwk15** [mdn/sprints#3379] opened 2020-06-17 09:07 UTC
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [x] Correction or update

# Details

I really get a lot out of MDN and appreciate all the documentation. It's a tremendous help to me, and to the whole web-developing community.

I was wondering if in the "Browser compatibility" section you could include the date (month+year? year?) of each browser version (even just as a tooltip). Such an addition would make it much easier to judge how widely adopted a given feature is for those of us who don't keep browser version dates in our heads. 

This request applies to all pages with a "Browser compatibility" section.

I appreciate your help. Thanks so much for this great site!

**Comment by Elchi3** [comment] 2020-06-23 13:35
Thanks for your request. I'm marking this as a duplicate of https://github.com/mdn/kumascript/issues/1119

**Closed by Elchi3** 2020-06-23 13:35 UTC
